### ISSUE TITLE
Spelling it's

### ISSUE THREAD

**Issue by zeehio** [rmflight/researchBlog_blogdown#1]
Thanks for your post on IRanges.

I noticed in the paragraph when you mention the red black trees there is an "it's" that should be an "its". I would submit a PR, but I believe you did not yet push the article to the repository :-)

Wonderful blog by the way!

**Comment by rmflight** [comment]
Thanks @zeehio, you are correct!

**Comment by rmflight** [comment]
Fixed, changes should be live shortly!
