### ISSUE TITLE
About pls-da

### ISSUE THREAD

**Issue by xie186** [rmflight/researchBlog_blogdown#2]
Hi Robert,

Thanks for the post about random forest and PLS-DA. I have a question:
what's the minimum sample size for you to perform PLS-DA based on you experiences or the paper you read? Thanks in advance. 

Best,
Shaojun

**Comment by rmflight** [comment]
Yikes. I really don't know Shaojun. I don't do PLS-DA, but I've seen plenty of people do it with 3 samples in each group. I wouldn't do that, personally. I get scared of doing t-tests with three in each group.

**Comment by xie186** [comment]
Thanks for your prompt response. I read this post by you: https://rmflight.github.io/post/random-forest-vs-pls-on-random-data/. So I started this issue to get some advice.
